
#rest template data compression encode and decode
#https://www.springcloud.io/post/2022-05/resttemplate-gzip/#gsc.tab=0

server:
  port: 8082

  compression:
      enabled: true
      mime-types: application/json,application/xml,text/html,text/xml,text/plain
      min-response-size: 2048

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    config:
      import-check:
        enabled: false
  application:
      name: orders
  datasource:
    initialization-mode: always
    url: jdbc:mysql://localhost:3306/pro
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


#for zipkin to have all the matrices ==> change probability to 1
#docker run -d -p 9411:9411 openzipkin/zipkin
  zipkin:
    base-url: http://zipkin-server:9411

management:
  tracing:
    sampling:
      probability: 1.0

#configure logging to include trace and span IDs by adding
logging:
  pattern:
    level: "%5p [${spring.zipkin.service.name:${spring.application.name:-}},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]"
