# data compression
#https://www.baeldung.com/json-reduce-data-size


#enable GZIP compression for HTTP responses by adding the following configuration
  # new response time :151 ms  Old response time:1366 ms
server:
  port: 8081
  # original 627kb compressed to 127kb
  compression:
      enabled: true
      mime-types: text/html,text/plain,text/css,application/javascript,application/json
      min-response-size: 1024

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


spring:

  data:
    elasticsearch:
      cluster.name: elasticsearch.yml
      client:
        host: localhost
        port: 9300
  cloud:
    config:
      import-check:
        enabled: false
  application:
    name: products
  datasource:
    initialization-mode: always
    url: jdbc:mysql://localhost:3306/pro
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  zipkin:
    base-url: http://zipkin-server:9411

#for zipkin to have all the matrices ==> change probability to 1 ,
  #include trace and span ID done automatically
management:
  tracing:
    sampling:
      probability: 1.0

#configure logging to include trace and span IDs , log file
logging:
  file:
    name: I:/logs/elk-stack.log
  level:
    root: INFO

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
# Cucumber Configuration
cucumber:
  plugin: pretty


  publish:
    enabled: true